### ISSUE TITLE
3128 dev build python syntax error

### ISSUE THREAD

**Issue by audiolion** [SublimeText/PackageDev#100]
Hey I found this today, not sure why it occurs but in any *.py file if you do `self.get_object()` the `self`highlighting disappears, any other reference to `self.object()` or `self.get_obj()`, etc. work as expected.

**Comment by keith-hall** [comment]
I'm not able to reproduce this:
![python self 3128](https://cloud.githubusercontent.com/assets/11882719/24974852/4ceb7afa-1fcc-11e7-974f-8af5f6f1fc45.png)

the `self` in each case is scoped as `source.python meta.function-call.python meta.qualified-name.python variable.language.python`

**Comment by audiolion** [comment]
My apologies, this was related to a custom syntax I was using https://github.com/squ1b3r/Djaneiro.

**Comment by FichteFoll** [comment]
(This issue also has nothing to do with PackageDev itself.)
