### ISSUE TITLE
[Syntax Def] Syntax gets confused with YAML multiline strings

### ISSUE THREAD

**Issue by rwols** [SublimeText/PackageDev#108]
Pictures say it all I guess:

![schermafbeelding 2017-05-28 om 16 23 31](https://cloud.githubusercontent.com/assets/2431823/26529555/1f6a7878-43c2-11e7-8329-0478d40e97a0.png)
![schermafbeelding 2017-05-28 om 16 23 45](https://cloud.githubusercontent.com/assets/2431823/26529556/1f96921e-43c2-11e7-90df-8141f82313eb.png)

Sublime seems to parse this OK.

**Comment by FichteFoll** [comment]
They are valid YAML, but I assumed (or hoped, rather) that people wouldn't use block scalars for key like this. Will have to think about whether adding support for it will be worth it or not.

**Comment by rwols** [comment]
Yeah, it's the first time I'm using it. I thought if I just use a multi line string at two places then my whole file is nicely indented with 80 chars.

**Comment by FichteFoll** [comment]
FYI, you can just continue plain scalars on the next line, if it is indented with more spaces. This should be highlighted fine. Newline and surrounding spaces will be collapsed at parse time.

**Comment by rwols** [comment]
This is what I did and it indeed works fine. Thanks!
