### ISSUE TITLE
Deprecate sublime_lib

### ISSUE THREAD

**Issue by guillermooo** [SublimeText/PackageDev#11]
I could imagine not many people are using it, including myself. It's just too much to ask users to install this package solely for a few helpers. If having a shared library for packages is a good idea, there must be a better way of implementing it.

So I propose deprecating the library and eventually dropping the ``aaa.py`` stuff altogether. The helpers sould remain visible for this package only.

One side-effect is also desirable: because we wouldn't need to gurantee that certain modules are always imported first,  we could drop the ``AAA`` from the name.

**Comment by FichteFoll** [comment]
Imo as a first step we can make the library private and only use relative imports (or absolute for ST2) instead of messing with paths. This will be a band aid fix until a dedicated sublime_lib or sublime_utils dependency exists.

**Comment by FichteFoll** [comment]
Done on `develop` branch.

**Comment by FichteFoll** [comment]
I derped a bit and forgot to test in ST3 after the changes. Fixed via 93824e033d2f4484b6a0453fe75f17406775a088.
