### ISSUE TITLE
Completions highlight issues

### ISSUE THREAD

**Issue by Resike** [SublimeText/PackageDev#112]
\", \t, (, ), [, ], and , in the auto-completion triggers is not recognised properly.

{
	"trigger": "time\t([\"timeDesc\"])",
	"contents": "time(${1:[timeDesc]})$0",
},

It would be nice to highlight the \" and \t and accept every character in the string itself, just like on the "contents".

**Comment by keith-hall** [comment]
This should get covered as part of https://github.com/SublimeText/PackageDev/issues/67

**Comment by Resike** [comment]
Nice, it would be nice if you could also add a way to create comments in .sublime-completions files.

**Comment by FichteFoll** [comment]
This will be done as well.

**Comment by keith-hall** [comment]
looks like this has been fixed in https://github.com/SublimeText/PackageDev/pull/123 💯
