### ISSUE TITLE
adding all the formulas and command pallet implementations of sublime text to a framework, which can be used in any ide

### ISSUE THREAD

**Issue by tiagmoraismorgado** [SublimeText/PackageDev#121]
_it would be interesting if we could:_

- **_add all the formulas and command pallet implementations of sublime text to a framework, which can be used in any ide (like atom, qt, xcode, visual studio, etc.)_**

**Comment by FichteFoll** [comment]
I'm afraid I don't understand.

**Comment by tiagmoraismorgado** [comment]
i can put it clear. there are a whole number of shorcuts and plugins in sublime text. what i aim with this is that we make an extensive collection of those and make it available and fully implemented for other IDEs, as a framework, or simply as extensions

**Comment by FichteFoll** [comment]
So basically you're describing something that allows writing a cross-text-editor package that is converted to the formats used by multiple text editors?

This exceeds the purpose of this package by a longshot and I'm not going to add anything like this. There are a couple packages or tools that convert some configuration files between ST and Atom (which uses cson) and to my knowledge VS code uses tmLanguage files still, but I have no idea about the specifics of their resource files.

Plugins are inconvertible either way.

**Comment by FichteFoll** [comment]
The Atomizr package was designed for this purpose. You can read more about it here: https://forum.sublimetext.com/t/atomizr-reboot/27684?u=fichtefoll

I won't implement this into PackageDev.
