### ISSUE TITLE
problem in taking input in sublime text 

### ISSUE THREAD

**Issue by MotiBaadror** [SublimeText/PackageDev#132]
Os: win 10 
I have added mingw compiler and also added it to the path 
but when i run code its showing 
C:/Program Files (x86)/mingw-w64/i686-7.1.0-posix-dwarf-rt_v5-rev2/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file C:\Users\Moti Baadror\Desktop\youtube/main.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
[Finished in 1.8s]

**Comment by FichteFoll** [comment]
This doesn't look like an issue with PackageDev to me.

**Comment by tanmayrsm** [comment]
are yar answer de na koi

**Comment by Aman333Saxena** [comment]
> are yar answer de na koi
@tanmayrsm 

This means you are building an already running file. In order to build the file successfully, first kill the previously running file, then execute the same. I hope, it helps.
