### ISSUE TITLE
Side-by-side settings have does not have a quick link for editing them

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/PackageDev#136]
When I open the Sublime Text settings on:

![image](https://user-images.githubusercontent.com/5332158/30267649-9eecc4d0-96b9-11e7-9f5d-8d1b9c6b4950.png)

I got the quick link:

![image](https://user-images.githubusercontent.com/5332158/30267709-d0e73e0c-96b9-11e7-8595-e75ad4f01237.png)

But when I pick up a setting with:

1. ![image](https://user-images.githubusercontent.com/5332158/30267743-eacd9776-96b9-11e7-8ccd-04900eb32461.png)
1. ![image](https://user-images.githubusercontent.com/5332158/30267775-fe827ef8-96b9-11e7-8e21-7cde7fea7a15.png)

I do not get the `quick` edit icon button:

![image](https://user-images.githubusercontent.com/5332158/30267799-144b148e-96ba-11e7-811d-3c848e739614.png)

**Comment by keith-hall** [comment]
Presumably this is a bug with whatever package gives you the "Side-by-Side" command palette entries, in that it doesn't set the relevant setting on the view...

**Comment by evandrocoan** [comment]
I use this package: https://github.com/jgbishop/sxs-settings Do you use some different one which works?

**Comment by FichteFoll** [comment]
The functionality was designed for the `edit_settings` command provided by the Default package.

sxs-settings needs to assign the settings `edit_settings_view` and `edit_settings_other_view_id` to both opened views.

**Comment by evandrocoan** [comment]
Thanks for explaining! I fixed the package on my fork so now it working correctly.
