### ISSUE TITLE
[Modern SQL] High light color for SQL

### ISSUE THREAD

**Issue by dannyeuu** [SublimeText/PackageDev#138]
There are some improvments for SQL inside Python or other language with SQL:2016 (modern SQL stuffs)
like:
- OVER
- PARTITION
- ROW_NUMBER()
- FILTER

There are not actually detected:
![screenshot from 2017-09-11 15-14-36](https://user-images.githubusercontent.com/6808348/30289933-2471a888-9704-11e7-86f4-173e0cbb3701.png)

**Comment by keith-hall** [comment]
If you want to suggest improvements to the SQL highlighting that comes with ST, you should file an issue at https://github.com/sublimehq/Packages, if one doesn't already exist.

This PackageDev repo is for the ST plugin that helps to build ST packages, it isn't a catch all repo for all issues with any ST package.

Worth reading is this discussion about how there will hopefully be separate syntax definitions in ST for each SQL dialect in future: https://github.com/sublimehq/Packages/issues/630#issuecomment-248919393
