### ISSUE TITLE
No command args completion in menus available

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#139]
The `SublimeTextCommandArgsCompletionListener` defines a selector containing 

```
        "- meta.value.json "
        "- meta.mapping.json meta.mapping.json "
        "- meta.sequence.json meta.sequence.json "
```

This causes command arguments not being offered for commands of sub-menu items in a `*.sublime-menu` file as all of them are scoped as `meta.value.json` or `meta.sequence`.

#### Example:

```JavaScript
[
    // ...
    {
        "caption": "Edit",
        "mnemonic": "E",
        "id": "edit",
        "children":
        [
            { "caption": "-" },
            {
                "caption": "Revert Change to Commit",
                "command": "git_gutter_revert_change"
            },
            {
                "caption": "Copy Content from Commit",
                "command": "git_gutter_copy_from_commit",
                "args": {   // not offered
                    "": ""  // not offered
                },          // not offered
            },
            { "caption": "-" },
        ]
    },
    // ...
]
```

This issue leads to a general question for all `json.sublime` syntaxes. 

The JSON file does not only provide a key-value architecture as reflected by the current scopes, but is more a kind of tree structure as known from xml. Even though the `"children": [...]` can be interpreted as key-value pair, the value `[...]` here is not a real value but the next level of the tree, which may contain the same items as the top-level sequence, which is not scoped as value!

I am wondering if we can find a way to add some scopes to the child elements, which reflect the tree structure better. I wouldn't suggest to remove the key-value scopes in general as they are part of the default json syntax, but maybe we'd add some `... .sublime-menu` scopes to overcome that issue.

The reason for that idea/request is the need to distinguish between _key-completions_ (e.g. "caption", "command", ...) and _value-completions_. 

This issue is triggered as "args" is a key-completion, but the sub-menu items are scoped as value and therefore excluded by the current selector.

We could just remove the lines from selector, but this causes the keys to be offered in values, too.

**Comment by r-stein** [comment]
IMO we should just add a special case to the selector to handle menus. Using the value structure is also good for menus, because this enables a colorscheme to show different colors for different nesting levels. However they are somehow special, because the definition is recursive for the children array entries and we just need to take care of that in the selector. We may change it to something like this (to not execute that removal inside menu files):

```py
"- ((meta.value.json | meta.mapping.json meta.mapping.json | meta.sequence.json meta.sequence.json) - source.json.sublime.menu)"
```
