### ISSUE TITLE
Cannot insert a `^` character

### ISSUE THREAD

**Issue by rwols** [SublimeText/PackageDev#141]
I cannot seem to insert a `^` character inside of a comment in a syntax test file anymore. When turning on key logging and command logging, the console reads:

```
chr evt: ^ (0x5e)
command: packagedev_suggest_syntax_test
```

**Comment by rwols** [comment]
I'm on OS X 10.12, build 3142 if it helps.

**Comment by FichteFoll** [comment]
All I can say so far is that it works for me and a couple other users (as mentioned on the Discord).

**Comment by keith-hall** [comment]
Do you perhaps have an override @rwols?

**Comment by rwols** [comment]
I've upgraded from 3142 to 3144 and the issue seems to be gone! No idea what caused it :(
