### ISSUE TITLE
Syntax in SYNTAX TEST files is not applied

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#150]
PackageDev seems to actively apply the syntax to a _syntax_test_ ..._ file, which works fine if the header looks like that:

```
; SYNTAX TEST "Packages/CNC Sinumerik 840D language support/gcode/s840d_gcode.sublime-syntax"
```

If the header contains the syntax file only,  _Plain Text_ is assigned as syntax.

```
; SYNTAX TEST "s840d_gcode.sublime-syntax"
```

If PackageDev is disabled, in both cases Sublime Text assigns the correct syntax to the opened file.

Therefore I'd expect the same behavior with PackageDev enabled.

**Comment by keith-hall** [comment]
So I guess it should use `sublime.find_resources` to find the full path to the syntax file?

**Comment by FichteFoll** [comment]
Does St internally search for files with that name in the entire resources or only in the same directory?

**Comment by keith-hall** [comment]
Entire resources - I just made a simple test creating `syntax_test_test.txt` in `Packages/ASP/` containing

```
-- SYNTAX TEST "Markdown.sublime-syntax"
# h1
-- <- markup.heading
```

and it passed - changing to `- markup.heading` made it fail
