### ISSUE TITLE
Scoping on .YAML-tmLanguage vs .sublime-syntax

### ISSUE THREAD

**Issue by runxel** [SublimeText/PackageDev#162]
Scoping doesn't work when one uses the [YAML structure of the .sublime-syntax](http://www.sublimetext.com/docs/3/syntax.html) files, as in use since ST build 3084.

**Comment by FichteFoll** [comment]
I don't understand this issue. 

What are you doing, what is happening and what do you expect? Include screenshot if the help convey your point.

**Comment by runxel** [comment]
I'm sorry I wasn't clear enough here.
The attached screenshot will give you the full misery.
The left is a .YAML-tm-language file, which looks great. The right is a .sublime-syntax file, which doesn't.
Both have the syntax set to "Sublime Text Syntax Def (YAML)".

![highlight](https://user-images.githubusercontent.com/2277182/31623592-2db8df76-b2a0-11e7-826f-39780c70e0a5.png)

**Comment by FichteFoll** [comment]
You should use "Sublime Text Syntax Definition (YAML)" for the right side.

In fact, it appears you are using an outdated version of PackageDev since the "Sublime Text Syntax Def (YAML)" definition has been renamed to "TextMate Syntax Definition (YAML)".

**Comment by runxel** [comment]
Oh my bad! You're right...  
I was in fact using a very old version.  
How's that? Any idea why a package wouldn't update?

**Comment by FichteFoll** [comment]
The most likely reason would be either installing manually or having automatic updates disabled. You should check your PC settings file.

You can force-upgrade packages with "Package Control: Upgrade Package".

**Comment by runxel** [comment]
Interestingly neither is the case here...  
That's why I never checked on which version I actually am – for me it was out of realm of possibility.
