### ISSUE TITLE
tmPreferences symbol transformations don't require a leading `s`

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/PackageDev#172]
Random example file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Symbol Index</string>
    <key>scope</key>
    <string>source.gdl entity.name.function</string>
    <key>settings</key>
    <dict>
        <key>showInIndexedSymbolList</key>
        <integer>1</integer>
        <key>symbolIndexTransformation</key>
        <string>/\"([:word:]+)\"/$1/;</string>
    </dict>
</dict>
</plist>
```

**Comment by keith-hall** [comment]
It does if you stick an `s` before the `/` - I had the impression that it is necessary, no?
![image](https://user-images.githubusercontent.com/11882719/32514246-1f1c556c-c405-11e7-9386-f837bdcff578.png)

**Comment by runxel** [comment]
@keith-hall the [css package](https://github.com/sublimehq/Packages/blob/master/CSS/Symbol%20Index.tmPreferences) doesn't do it... 🤷‍♂️

**Comment by FichteFoll** [comment]
Ehm yeah, I seem to remember reading contexts that do this. Yes, the `s` is required and the syntax does indeed already help you spot that issue (at least if you know that regex replacements are highlighted).

Carry on.

**Comment by runxel** [comment]
Why does the `s` do anyway?
Found no explanation on this topic...

**Comment by FichteFoll** [comment]
It's short for "substitution" and frequently used to denote a regex replacement in old-ish applications like `vim`, `sed` et al.
