### ISSUE TITLE
Menu Options Disabled

### ISSUE THREAD

**Issue by depperm** [SublimeText/PackageDev#176]
Under Tools->Packages->Package Development, all of the options are grayed out (see attached). It doesn't matter if it is a new file or a file I open. Is there a precedent for this (something I'm obviously doing wrong)? Or could it be some other setting I have that is interfering with it?
![sublime](https://user-images.githubusercontent.com/8761660/33949772-99b1f05c-dff8-11e7-9c60-068412410cce.png)

**Comment by FichteFoll** [comment]
Looks like something is messed up with your local setup.

Please paste the contents of your console.

**Comment by depperm** [comment]
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/damarsha/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/damarsha/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/damarsha/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Package Control", "Vintage"]
pre session restore time: 0.300419
startup time: 0.382419
first paint time: 0.382419
scan: /J/emarshal_jup/jupsys has been seen before, skipping (using inode) previous path: /J/emarshal_jup/jupsw inode: 36
Unable to fetch update url contents
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_core in C:\Users\damarsha\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 26, in <module>
ImportError: No module named 'mdpopups'
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.changes
reloading plugin BracketHighlighter.support
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\damarsha\AppData\Roaming\Sublime Text 3\Packages\PackageDev\main.py", line 22, in <module>
    from .plugins_ import *  # noqa
  File "C:\Users\damarsha\AppData\Roaming\Sublime Text 3\Packages\PackageDev\plugins_\__init__.py", line 4, in <module>
    from .command_completions import *  # noqa
  File "C:\Users\damarsha\AppData\Roaming\Sublime Text 3\Packages\PackageDev\plugins_\command_completions\__init__.py", line 11, in <module>
    from .commandinfo import (
  File "C:\Users\damarsha\AppData\Roaming\Sublime Text 3\Packages\PackageDev\plugins_\command_completions\commandinfo.py", line 5, in <module>
    import yaml
ImportError: No module named 'yaml'
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
rule #anon_expect_regexp_4 has a scope name, but is unreachable, so the name will never be used
rule #anon_expect_regexp_2 has a scope name, but is unreachable, so the name will never be used
rule #anon_expect_regexp_5 has a scope name, but is unreachable, so the name will never be used

**Comment by r-stein** [comment]
Press ctrl+shift+p and run *Package Control: Satisfy Dependencies*

**Comment by r-stein** [comment]
PS. It looks like you have Package Control disabled: Select *Preferences > Settings* and on the right side remove `"Package Control"` from the `"ignored_packages"`.

**Comment by depperm** [comment]
Yep that was it, thank you for your help.

**Comment by lspitzner** [comment]
Is there a way to install deps without PackageControl? I am not a fan of some opaque package manager installing random stuff without my control. I already have one OS running.

Alternatively, are the functionality like converting between the syntax definition formats exposed in some other fashion? Some commandline script perhaps? These scripts should be rather trivial, right?

**Comment by r-stein** [comment]
@lspitzner Yes you can just download the dependency and put the corresponding subfolder (e.g. `st3/thedependency` into the Sublime Packages folder.

**Comment by lspitzner** [comment]
@r-stein I assume the relevant dependencies can be transitively extracted from `/dependencies.json`, correct? And how do i turn a dependency name into an URL? It seems non-trivial for something such as `pyyaml`.

**Comment by r-stein** [comment]
@lspitzner You can use this json file to resolve the names: https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json

**Comment by lspitzner** [comment]
thanks!

**Comment by FichteFoll** [comment]
I suggest placing manually downloaded depedencies into `$Data/Lib/python3.3` instead, since that folder is already included in `sys.path`. After extracting the proper folder, of course.
