### ISSUE TITLE
You MUST use spaces! error: Syntax tests do not work properly with tabs as indentation.

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/PackageDev#177]
So, I press `Ctrl+P` and start typing a file I would like to open, then BAM! You do not even let me complete type the file name `gotolasteditenhanced`.

![image](https://user-images.githubusercontent.com/5332158/34188629-964d7aa0-e51e-11e7-9951-2080b6a5ce30.png)

I would happen to accidentally hit a syntax file which uses `tabs as indentation`:
```python
File: Data/Packages/PackageDev/plugins_/syntaxtest_dev.py
29: def _show_tab_warning():
30:     sublime.error_message("Syntax tests do not work properly with tabs as indentation."
31:                           "\n\nYou MUST use spaces!")
32: 
```
Your warning seem too aggressive popping up on a error message dialog. Also, very frustrating while using the `Ctrl+P`/Go To Anything... feature.

Why not just using `print` on the user console, perhaps also a `sublime.status_message` instead of `sublime.error_message` or `sublime.message_dialog`?

**Comment by FichteFoll** [comment]
Well, I specifically wanted this to get in the way of user experience so the user can fix their faulty indentation settings for syntax test files, so a print message on the console is a no-go.

There is no easy way for me to find out whether a view has been opened transiently from the Go To Anything panel and delay the message until it was *really* opened. I guess I could try to see whether `on_activated` messages can do any good for me, although it would require me to rework the logic around this "feature" quite a bit.

**Comment by FichteFoll** [comment]
Would be a lot easier if I could just check whether a quick panel is visible :/

Suggestions welcome, otherwise I'm inclined to not fix this (and rather fix https://github.com/sublimehq/Packages/issues/1361 instead).

**Comment by evandrocoan** [comment]
I think we check whether there is a quick panel open, if it is with focused. If not, we could wait Sublime Text allow to check whether the quick panel is open.

**Comment by FichteFoll** [comment]
>I think we check whether there is a quick panel open

I just mentioned that we can't, though, unless you know of some very hacky way that I'm not sure I'd want to rely on.
