### ISSUE TITLE
When I edit a settings files from an unpacked package, the edit arrows do not show up automatically

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/PackageDev#178]
If the package is inside a `.sublime-package` it shows up automatically when I open the file:

![image](https://user-images.githubusercontent.com/5332158/34235233-628a4da6-e5d7-11e7-9292-91ab0556f58b.png)

However when I edit a settings files from an unpacked package, the edit arrows do not show up automatically:

![image](https://user-images.githubusercontent.com/5332158/34234625-5fb0ceec-e5d3-11e7-9e52-acab50f1e82f.png)

If I edit a line, like adding an `a`, they show up:

![image](https://user-images.githubusercontent.com/5332158/34234639-7a229ea4-e5d3-11e7-9844-9a6cf5d361ca.png)

**Comment by FichteFoll** [comment]
I fixed this in 9x083df, but will delay it for the next release for when I have more stuff available. I just made one half an hour ago.
