### ISSUE TITLE
Cannot find settings under the file called `Base File.sublime-settings` 

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/PackageDev#196]
The package:
1. https://github.com/ehuss/Sublime-Wrap-Plus 

Name his settings file as `Base File.sublime-settings`. Then, it seems to cause `PackageDev` to not found the settings definitions for it:

![image](https://user-images.githubusercontent.com/5332158/46985693-03c0cd00-d0c2-11e8-921a-d4031a98b303.png)

**Comment by FichteFoll** [comment]
Hm, iirc this name is a relic from ST1 days and was replaced by the "Preferences" file we use today. If it still works for compatibility, we should probably add support for it. If it doesn't, we shouldn't and the Wrap Plus package should be updated to have that file renamed.

**Comment by evandrocoan** [comment]
I am not sure if Sublime Text accepts Base File as Preferences, but the plugin itself works with Base File as settings name. Despite it, why just not load every file with the `*.sublime-settings` as extension?

**Comment by FichteFoll** [comment]
I checked its source code (as well as I could on mobile) and wasn't able to find a `sublime.load_settings` call. It's all view.settings.

**Comment by evandrocoan** [comment]
Then, it seems Sublime Text itself is ignoring the file called `Base File.sublime-settings`

**Comment by FichteFoll** [comment]
I just verified that ST does indeed read files named `Base File.sublime-settings` as it does `Preferences.sublime-settings`, so the two can essentially be considered equivalent. Although the former is likely a backwards-compatible alias for the latter.
