### ISSUE TITLE
Invalid illegal highlighting of layer.tint = false/null

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#198]
PackageDev currently highlights `false` or `null` values for `"layerX.tint"` as `invalid.illegal`, which is wrong. Those values can be used to remove an attribute from the extended theme definition.

![image](https://user-images.githubusercontent.com/16542113/47373471-3b47fe80-d6ec-11e8-8614-fa01d0566307.png)

**Example:**

I created a _Windows 10.sublime-theme_ for Sublime Merge, based on the _Merge.sublime-theme_. I abuse the disclosure buttons to display as folders to make the commit dialog and the diffs look cleaner and more like a file list. In order to make the "folder" icon look normally I need to remove the `tint` attribute, which is applied to them in the _Merge.sublime-theme_. This is achieved by the rules of the first screenshot and works like a charm.

![image](https://user-images.githubusercontent.com/16542113/47373766-c4f7cc00-d6ec-11e8-9e9e-f38ecd89b435.png)

**Comment by FichteFoll** [comment]
Good to know. The docs didn't mention anything about this and none of the example themes I ran this through made use of it.
