### ISSUE TITLE
Remove sublime_lib and refactor to use new one from dependencies

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/PackageDev#203]
Now that sublime_lib is out, it might be an opportune time to do some refactoring:

- [x] Eliminate `edit.py` because ST2 isn't supported anymore.
- [x] Replace the included OutputPanel.
- [x] Replace the included Settings and ViewSettings.
- [ ] Use [ResourcePath](https://github.com/SublimeText/sublime_lib/pull/52) to simplify resource handling.
- [x] Use flags, e.g. in `SyntaxDefRegexCaptureGroupHighlighter`.

**Comment by FichteFoll** [comment]
Related: #11.

Pull requests welcome.

**Comment by FichteFoll** [comment]
Closing as the most significant improvements have been added over the following months and `ResourcePath` usage will be adjusted as needed when found in the code.
