### ISSUE TITLE
New theme elements

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/PackageDev#219]
I added the new attributes in #210 because they are needed for proper highlighting, but I haven't added the new elements because I'm waiting on an update of the official docs for those.

https://www.sublimetext.com/docs/3/dev/themes.html

I might also need to tweak the CSS `color` function since ST added a few custom modifier functions that the CSS4 draft does not have. Most likely need to implement my own version of that instead of relying on the shipped CSS.sublime-syntax. Update: fixed by #229

**Comment by FichteFoll** [comment]
@deathaxe considering that you added many new theme properties, attributes, etc recently, do you happen to know where we stand with out coverage currently?

**Comment by deathaxe** [comment]
Not for sure. Just added features/fixed stuff I realized in the Default.sublime-them while working on DA UI successor. Did not walk through the latest docs in detail.

**Comment by FichteFoll** [comment]
Went through the changelog on the docs and added all things still missing in 8411ab6825f82e63ee8a5a337e75fa20f9d4d3e3 and 351a4c9b197e73126402d96ba767d6e9499a495f.
