### ISSUE TITLE
Context names aren't added to the indexed reference list

### ISSUE THREAD

**Issue by mitranim** [SublimeText/PackageDev#221]
`Package/Sublime Text Syntax Definition/References - Context.tmPreferences` wants to add context names to references:

```xml
<dict>
    <key>scope</key>
    <string>source.yaml.sublime.syntax meta.include variable.other</string>
    <key>settings</key>
    <dict>
        <key>showInIndexedReferenceList</key>
        <integer>1</integer>
    </dict>
</dict>
```

As far as I can tell, context names that appear in `include`, `push`, `set`, `push: []`, `set: []` aren't added to the reference list. Probably because they're also scoped as `string.unquoted` in all of those places.

**Comment by keith-hall** [comment]
see https://github.com/SublimeText/PackageDev/pull/213, presumably you need to patch your `Packages/Default/symbol.py` to get this working

**Comment by mitranim** [comment]
Ooh didn't notice that. Thanks for the pointer.
