### ISSUE TITLE
Showing empty default theme settings

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/PackageDev#245]
1. ![image](https://user-images.githubusercontent.com/5332158/54496810-39b4e800-48d2-11e9-8498-2fce116102b8.png)

1. ![image](https://user-images.githubusercontent.com/5332158/54496801-19852900-48d2-11e9-97a3-d5fe8f45c37f.png)

Edit default Color Scheme Worked: (but note, it is directly installed on the loose `Packages` directory:
![image](https://user-images.githubusercontent.com/5332158/54496822-551ff300-48d2-11e9-9bbb-47e3adcf41c5.png)

**Comment by FichteFoll** [comment]
Cannot reproduce. Both commands open a respective file in the User package with the intended template for me.

**Comment by evandrocoan** [comment]
Thanks for looking into. I noted this, so later I can look into and try to fix it.
