### ISSUE TITLE
Did the autocomplete for syntax tests break?

### ISSUE THREAD

**Issue by michaelblyons** [SublimeText/PackageDev#247]
I used to get a suggestion for the longest matching string when I typed `^^^`s on a comment line in a syntax test file. This is no longer happening for me.

I can get by with [the Linter plugin](https://github.com/FichteFoll/SublimeLinter-contrib-sublime-syntax), but I had to take [#4](https://github.com/FichteFoll/SublimeLinter-contrib-sublime-syntax/issues/4) and extend the `wait()` even longer.

**Comment by FichteFoll** [comment]
Could you be more specific, i.e. provide steps for reproduction? It works for me.

**Comment by michaelblyons** [comment]
Interesting. The autocomplete works on, say, [this file][1], but not on [this one][2].

[1]: https://github.com/michaelblyons/SublimeSyntax-HTML-CSharp/blob/master/tests/syntax_test_ashx.ashx
[2]: https://github.com/robballou/sublimetext-sshconfig/blob/master/Tests/syntax_test.ssh_config

**Comment by michaelblyons** [comment]
I got it. The detection in [plugins_/syntaxtest_dev.py][1] is not recognizing the file as a test. It starts working if I rename the file so that the part before the `.` (e.g. before the file extension) has _anything_ in addition to `syntax_test`.

[1]: https://github.com/SublimeText/PackageDev/blob/master/plugins_/syntaxtest_dev.py

**Comment by FichteFoll** [comment]
So, uhm, I assume the reason you closed this is because ST doesn't recognize that file as a test file either? I wanted to verify that before coming back to you, but haven't been able to.

**Comment by michaelblyons** [comment]
ST does recognize it, but as long as I know why it's happening, I can just rename my tests.
