### ISSUE TITLE
 WARNING: command "duplicate_line" in the Default package is defined in the built-in metadata file, probably it should not be

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/PackageDev#252]
I just saw this in my console. I do not know how to reproduce this message. What it means?
```
reloading plugin HighlightWordsOnSelection.word_highlight
[PackageDev.plugins_.command_completions.commandinfo] WARNING: command "delete_word" in the Default package is defined in the built-in metadata file, probably it should not be
[PackageDev.plugins_.command_completions.commandinfo] WARNING: command "duplicate_line" in the Default package is defined in the built-in metadata file, probably it should not be
[PackageDev.plugins_.command_completions.commandinfo] WARNING: command "swap_line_down" in the Default package is defined in the built-in metadata file, probably it should not be
[PackageDev.plugins_.command_completions.commandinfo] WARNING: command "swap_line_up" in the Default package is defined in the built-in metadata file, probably it should not be
reloading plugin HighlightWordsOnSelection.word_highlight

```

**Comment by FichteFoll** [comment]
Which build are you on? Those commands were moved to the core recently, which is why we had to add them to the data. I should probably not make this a WARNING log event, seeing that's the default log level.

**Comment by evandrocoan** [comment]
I use build 3207 of Sublime Text. Why PackageDev is checking these things?

**Comment by FichteFoll** [comment]
For debugging the provided command data.

**Comment by evandrocoan** [comment]
You mean checking for defined duplicate commands?

**Comment by FichteFoll** [comment]
No, it's just that we provide command name and argument completions for built-in commands as well as those defined in plugins, but since the built-ins can not be parsed dynamically we provide a base config with those commands and their arguments. See the source code of the related module (it's in the log record).
