### ISSUE TITLE
builtin color completions in .sublime-color-scheme files

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/PackageDev#260]
should builtin colors be suggested in color scheme files
![bc](https://user-images.githubusercontent.com/33235928/66082953-91175e80-e56b-11e9-99d1-1fd7b95ad1dc.png) ?

**Comment by FichteFoll** [comment]
No, they don't work in color schemes because those are the source for these. defining the variables by yourself, however, will take priority over ST dynamically determining them.

**Comment by AmjadHD** [comment]
so it should be constrained to the keys in the variables section ?

**Comment by FichteFoll** [comment]
I'll take a closer look when I'm at a pc later.
