### ISSUE TITLE
Add color names completions

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/PackageDev#261]
It will be convenient to provide completions for color names (e.g in the a .sublime-color-scheme file the foreground value)

**Comment by FichteFoll** [comment]
Can you give an example? Do you mean css (or rather X) color names like `black`?

**Comment by AmjadHD** [comment]
>Do you mean css (or rather X) color names like black?

[css colors](https://www.sublimetext.com/docs/3/color_schemes.html#css_colors)

**Comment by FichteFoll** [comment]
Hm, not exactly a fan, as within a color scheme your would be more interested in a carefully selected set of colors that complement each other and proposing a set of constants that have been specified by some people at some point are not helpful in that regard.

Opinions?

**Comment by AmjadHD** [comment]
>Proposing a set of constants that have been specified by some people at some point are not helpful in that regard

since these are allowed in sublime text, for the sake of completeness, I believe it is better to include them in the completions.

**Comment by AmjadHD** [comment]
I think there are users that would want to test these colors, the completions will make the iteration and testing process easy.

**Comment by keith-hall** [comment]
I also find it highly unlikely that (m)any color scheme authors would choose to use a named color. In CSS completions (for phantoms etc) it *may* make sense (and it would be handled by a separate package, not PackageDev), but IMO not for color schemes.

**Comment by FichteFoll** [comment]
PD aims to emphasize usage of *best practices* for resource files, which includes for example highlighting dot-prefixed setting names as a method of namespacing. Adding completions for CSS names, which Will or Jon even called a mistake[^1], if my memory serves me right, is something I would consider promoting a *worst practice* and thus goes against PD's goals.

[^1]: As much of a mistake as needing backwards compatibility with existing schemes for TextMate can be, I guess.

We have syntax highlighting for them (through the CSS syntax), which means we support the colors, but we don't want to suggest people to *actually* use them.
