### ISSUE TITLE
Missing scope and style settings for highlighting capture groups in .sublime-syntax files

### ISSUE THREAD

**Issue by Serega124** [SublimeText/PackageDev#267]
For syntax test highlighting the package has `syntax_test.highlight_scope` and `syntax_test.highlight_styles` settings:
https://github.com/SublimeText/PackageDev/blob/86c16e3efd493b7f4dc4d0baf93a5214faa19407/plugins_/syntaxtest_dev.py#L187-L188
These settings are present in `PackageDev.sublime-settings`. But relevant settings for capture group highlighting are missing:
https://github.com/SublimeText/PackageDev/blob/d0b3dc2b3a26e2b64ff0513e7e7ce090bfba44eb/plugins_/syntax_dev.py#L39-L40
So I don't know which scope used for highlighting captures and how to style it in my color scheme.

**Comment by FichteFoll** [comment]
Thanks for the heads up. Since they haven't been exposed in the default settings file yet, I'm going to rename those to have a dot for namespacing. You can, however, already use these settings by these names.
