### ISSUE TITLE
Add `mini_auto_complete` hidden setting

### ISSUE THREAD

**Issue by jrappen** [SublimeText/PackageDev#269]
For 4057+, I guess. Haven't tested support on earlier builds.

```js
    // when true, will show the best completion using a phantom
    // rather than a pop-up
    "mini_auto_complete": false,
```

Jon mentioned this on [![SublimeHQ Discord](https://img.shields.io/discord/280102180189634562?label=SublimeHQ%20Discord&logo=discord)](https://discord.gg/D43Pecu).

**Comment by FichteFoll** [comment]
Since Jon mentioned this to likely be scraped until a better/proper solutio is found, I would rather wait a bit for it to mature before having to remove the setting again.
