### ISSUE TITLE
Comment-toggle for theme/color-scheme files

### ISSUE THREAD

**Issue by michaelblyons** [SublimeText/PackageDev#272]
It'd be nice to add a `.tmPreferences` file to toggle comments with <kbd>Cmd</kbd>+<kbd>/</kbd> for `.sublime-theme` and `.sublime-color-scheme` files.

**Comment by FichteFoll** [comment]
Works for me already. These should be matched by the tmPreferences file in the JavaScript package because our scopes are `source.json.sublime.{theme,scheme}`.

**Comment by michaelblyons** [comment]
https://github.com/sublimehq/Packages/commit/5ce22961f1b0386bf91edfd715d41866f39ce81a#diff-43ae7c7377aa45c8a6985cba517991ae

So maybe make a `source.json.sublime` one? Now I understand why I thought this was working before. 😉

**Comment by michaelblyons** [comment]
Oops. I'm a dummy. All I had to do was wire up the (new) JSON folder to my packages.

**Comment by FichteFoll** [comment]
Ah right, I forgot the package has been split recently. Either way, it will work on normal setups.
