### ISSUE TITLE
Incorrect syntax highlighting for sublime-theme

### ISSUE THREAD

**Issue by absop** [SublimeText/PackageDev#274]
When I open the source file of the Material-theme-lighter theme, large part of the view was highlighted in RED means illegal syntax. But the there works well.

**Comment by FichteFoll** [comment]
Please include the or a minimal sample file for reproduction and a screenshot.

**Comment by FichteFoll** [comment]
Okay, I found out where it breaks. `"layer0.texture": [255, 255, 255, 255],`
