### ISSUE TITLE
[Completions] Highlight supported html tags in the details field

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#291]
ST 4073+ supports html in the "details" key of a sublime-completion.

see: https://github.com/sublimehq/sublime_text/issues/3093#issuecomment-612144800

They should be highlighted by the sublime-completion syntax.

**Comment by FichteFoll** [comment]
Just thinking out loud, but this is probably going to be a bit annoying due to being quoted and the command's href requiring double quotes for the args. We probably can't use `embed` because that.

**Comment by deathaxe** [comment]
Wouldn't be useful to embed the whole html syntax anyway due to the limited support of only few tags. Not yet having an idea about the quoted href, but the normal `<code>`, `<i>`, ... could propably receive a dedicated scope, just as feedback to see they are supported.
