### ISSUE TITLE
Add support for the comma-separated scope list synatx in sublime-syntax files

### ISSUE THREAD

**Issue by anima-libera** [SublimeText/PackageDev#307]
It is possible to define multiples scopes in a `scope:` field by separating them with commas like in
```
scope: meta.interface.xxx, entity.name.xxx, etc.xxx
```
however the syntax of sublime-syntax files doesn't really handle that correctly (only the first comma seems handled and the auto-completion breaks on the next capture for example).
This is not a big issue, but resolving it may add a `+` to the `SS++++` ranking of this extremely good package ^^.

**Comment by keith-hall** [comment]
Are you sure the commas don't become part of the scope?  (I'm not at a computer to check - the `show_scope_name` command on a token you've scoped with commas should reveal it) Typically scopes are stacked just with a space, no need for commas.

**Comment by anima-libera** [comment]
Oh, my bad, scopes are space-separated... I couldn't find this anywhere, I only found an answer on the Sublime Text forum that says that scopes are comma-separated. Commas on comma-separated lists of scopes do show up when using the `show_scope_name` command, but everything else seems to work fine just as if they where space-separated.
Sorry for this non-issue then.
But still: when using the comma-separated syntax in a sublime-syntax file, the first comma is given the scopes
```
source.yaml.sublime.syntax meta.block.contexts.sublime-syntax
```
and the second one is given the scopes
```
source.yaml.sublime.syntax meta.block.contexts.sublime-syntax string.unquoted.plain.out.yaml
```
as if commas were only partly supported (or maybe they have an other use that I am not aware of, since documentation on the sublime-syntax syntax is rare on the Internet ><).

**Comment by FichteFoll** [comment]
The first comma should definitely be part of a string scope, so I fixed that for the next release. However, commas and other special characters in scope names aren't really expected or supported. I haven't experimented with what characters are allowed, but you would certainly be unable to match a literal comma with a scope selector, since the comma is an operator there.
