### ISSUE TITLE
Any way to disable Quick-Edit Icons?

### ISSUE THREAD

**Issue by jasonhan-vassar** [SublimeText/PackageDev#334]
Is there an option to disable the quick edit arrows? I didn't see any in the package preferences.

**Comment by Ultra-Instinct-05** [comment]
Can you tell what is meant by "quick edit arrows" ? Maybe attach some screenshots for better understanding.

**Comment by jasonhan-vassar** [comment]
Sorry about that, I was referring to this feature: https://github.com/SublimeText/PackageDev/wiki/Settings#quick-edit-icons. There's a few screenshots.

**Comment by Ultra-Instinct-05** [comment]
If you are referring to that pencil icon feature (clicking will take that setting to the right hand pane), I am guessing there is no way to do that currently. From a look in the codebase, it looks like pencil phantom unicode is built if `edit_settings_view` is set to `base` but I don't think that's customizable. At least, I couldn't get it to work by setting something other than `base` in `PackageDev` settings.

**Comment by jasonhan-vassar** [comment]
I see, I kinda figured there wasn't a setting but I wanted to make sure. I just commented out [these lines](https://github.com/SublimeText/PackageDev/blob/master/plugins/settings/__init__.py#L147-L149) and restarted ST, which disables the pencils. It's kind of hacky but I think it's the best I'm going to get for a good while (if it ever gets in).

**Comment by FichteFoll** [comment]
This is a reasonable request, so I'm reopening the issue.
