### ISSUE TITLE
[settings] `"gtk_client_side_window_decorations"` missing tooltip

### ISSUE THREAD

**Issue by jrappen** [SublimeText/PackageDev#335]
`"gtk_client_side_window_decorations"` missing tooltip, is a hidden setting.

@benjaminschaaf mentioned this this morning on Discord to be implemented in the next build, so I assume this would be `Build 4098` and later.

**Comment by BenjaminSchaaf** [comment]
Build 4097. Note it's undocumented.

**Comment by jrappen** [comment]
PackageDev provides hints for undocumented settings via:

https://github.com/SublimeText/PackageDev/blob/master/Package/Sublime%20Text%20Settings/Preferences.sublime-settings-hints
