### ISSUE TITLE
PackageDev's Tab-Indentation-Error-Dialog interrupts Goto Anything

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#350]
Each time a syntax test file being detected to use tab indentation is displayed in Goto Anything preview, the following error dialog is displayed and Goto Anything Quick Panel closes. 

That's quite annoying.

![grafik](https://user-images.githubusercontent.com/16542113/132905236-83c365a3-4965-4160-a197-01d0101421ae.png)

Can the check be disabled for transient views?

**Comment by Ultra-Instinct-05** [comment]
Duplicate of https://github.com/SublimeText/PackageDev/issues/177
