### ISSUE TITLE
PackageDev wants to manipulate indentation settings for non-test files

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#365]
I am on `master` and see the following dialog on any file which uses tab indentation.

![grafik](https://user-images.githubusercontent.com/16542113/155893534-2dd32992-1742-446a-abc8-28d11504fe8c.png)

It should be limited to `syntax_test_...` files.

**Comment by roblav96** [comment]
Quick fix, add `PackageDev` to `ignored_packages` in your `Preferences.sublime-settings`
