### ISSUE TITLE
Tested syntax is not automatically applied to syntax_test_ files

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#368]
The following change disables the whole functionality of automatically assigning the tested syntax to a view  which displayes the related syntax_test_ file. Is that really intended?

https://github.com/SublimeText/PackageDev/commit/f29129a0228fb8f31fdd2c18c5152ba18a588648#diff-5f31bcd916c5ad34039b26d6c3c4104d8a009a9d4816eae5efdd104a34d1d97aR410-R414

If not, the `!=` operator should be replaced by `==`.

**Comment by FichteFoll** [comment]
Thanks, that was definitely not intended.
