### ISSUE TITLE
Python 3.10+ `with` statement highlighting issue

### ISSUE THREAD

**Issue by PedanticHacker** [SublimeText/PackageDev#386]
There seems to be a highlighting issue if there's Python code that has a `with` statement written like this:

```py
with (
    open(...) as file_1,
    open(...) as file_2,
):
    # Do something
```

This `with` statement syntax is available since Python 3.10, but the latest Sublime Text version 4143 highlights both `as` words and the enclosing `)` parenthesis as if there's a syntax error in the code.

Can you please take a look at this and fix it? Thank you.

**Comment by FichteFoll** [comment]
This was an issue with the default Python syntax (https://github.com/sublimehq/Packages/issues/3516) and has been fixed in build 4144 (https://github.com/sublimehq/Packages/pull/3519).
