### ISSUE TITLE
is there any way to install this without the command palette?

### ISSUE THREAD

**Issue by aaaaaaaaahhhhh** [SublimeText/PackageDev#396]
no matter what i do, who i talk to, what i install or where i ask, neither i nor anyone else on this planet can get the command palette open. is there any way to just install this without the command palette? where would i put the source code files?

**Comment by FichteFoll** [comment]
If you cannot open the Command Palette, your ST setup is either fundamentally broken or you're doing something wrong. Is the issue that the palette doesn't open at all or that Package Control isn't working? Does the palette open if you use the menu, i.e. *Tools > Command Palette…*? Do you see errors in the Console? (*View > Show Console*)

**Comment by FichteFoll** [comment]
I have no idea how the "Windows Terminal" has any relevance here. Could you provide a screen recording?

**Comment by aaaaaaaaahhhhh** [comment]
My mistake. I realize that I was trying to install Package Control instead of this. I don't know of any avenue to get help from the creator of Package Control so I'll just close this.
