### ISSUE TITLE
Add syntax definition for the new syntax format (using the new format)

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/PackageDev#57]
Hype!

**Comment by y0ssar1an** [comment]
I'm rewriting my CSS syntax definition in the new format and truly miss all the awesome productivity enhancements of AAAPackageDev. I'd love to see this enhancement.

BTW Thanks so much for this awesome package.

**Comment by chiefy** [comment]
:+1:

**Comment by FichteFoll** [comment]
This is now available on the latest pre-release version for ST versions >=3092. Please test and share your experiences.

To enable installation of pre-releases, open "Preferences: Package Control - User" via the command palette and add this:
```
	"install_prereleases":	["PackageDev"],
```

**Comment by keith-hall** [comment]
My experience is... "how did I ever live without it!?"
awesome work dude!

**Comment by FichteFoll** [comment]
Given that this has ben thoroughly tested by multiple people now, I'm assuming this to be feature complete and closing.

What follows are the other issues for the [3.0.0 milestone](https://github.com/SublimeText/PackageDev/milestone/3), which is mostly #67.
