### ISSUE TITLE
Future sublime_lib feature requests

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/PackageDev#70]
If you have any functionality requests that should be included in sublime_lib once it gets released as a Package Control dependency, tell us about it **in this issue**.

We will consider your requests and then decide whether we will add them to the module.

Features likely to be included:

- [ ] OutputPanel abstraction class
- [ ] ~~ST2- and ST3-compatible abstraction that allows making arbitrary edits to views from within WindowsCommands~~ ST2 is deprecated
- [ ] most of the current features in the view and path submodules, with additions and adjustments
- [ ] enum-like resolving for various flags provided in the `sublime` module
- [ ] something for settings with a callback that is only called when a relevant setting has been changed (compare InactivePanes package)
- [ ] mapping to convert ST and Python text encoding names ([via](https://github.com/jasjuang/sublime_cmake_format/blob/e7c1121418ac6ac72fea3a05b28fb153bfdd48ac/cmake_format.py#L22-L59))

**Comment by pradyunsg** [comment]
I am currently using this in an un-released package of mine and would love to see this available as a Package Control Dependency. I don't have any requests for features.

When can I expect this to land?

**Comment by FichteFoll** [comment]
That sounds like a great idea. However, I believe that is better suited to be a part of @scholer's [Logging Control](https://github.com/scholer/sublime_logging_control) package.

Unfortunately I can not give an ETA at this time.

**Comment by Thom1729** [comment]
Abstraction for sublime's various flag arguments. (As mentioned in #102.)

For instance, the following code:

```python
style_flags = 0
for style in styles:
    if style in [
        'DRAW_EMPTY', 'HIDE_ON_MINIMAP', 'DRAW_EMPTY_AS_OVERWRITE', 'DRAW_NO_FILL',
        'DRAW_NO_OUTLINE', 'DRAW_SOLID_UNDERLINE', 'DRAW_STIPPLED_UNDERLINE',
        'DRAW_SQUIGGLY_UNDERLINE', 'HIDDEN', 'PERSISTENT'
    ]:
        style_flags |= getattr(sublime, style)

self.view.add_regions(
    key='captures',
    regions=list(self.get_regex_regions()),
    scope=scope,
    flags=style_flags,
)
```

...could be replaced by:

```python
self.view.add_regions(
    key='captures',
    regions=list(self.get_regex_regions()),
    scope=scope,
    flags=sublime_lib.StyleFlags(styles),
)
```

The implementation could be based on [IntFlag](https://docs.python.org/3/library/enum.html#enum.IntFlag). Thus:

```python
if view.classify(point) in sublime_lib.ClassFlags('WORD_START', 'WORD_END'):
    pass

view.add_regions(
    key = 'key',
    flags = sublime_lib.ClassFlags.PERSISTENT | userflags,
)

def on_hover(point, hover_zone):
    print(sublime_lib.HoverZoneFlags(hover_zone))
    # "HoverZoneFlags.HOVER_TEXT"
```

**Comment by FichteFoll** [comment]
Unfortunately the `IntFlag` class [hasn't been backported to the `enum34` PyPI package](https://bitbucket.org/stoneleaf/enum34/src/f24487b45cd041fc9406d67441d2186ac70772b7/enum/__init__.py?at=default&fileviewer=file-view-default#__init__.py-5) (yet). Otherwise this is a great idea and certainly something I have in mind for these flags, since they are not as well organized as first-class members of the `sublime` module.

**Comment by FichteFoll** [comment]
Defered to a dedicated repo at the SublimeText org: https://github.com/SublimeText/sublime_lib

See the issue list for feature and implementation suggestions.
