### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by davidhq** [SublimeText/PackageDev#74]
I use Package Control and go to Install Package, but PackageDev is not found:

![screen shot 2016-03-31 at 12 55 09](https://cloud.githubusercontent.com/assets/3899/14173705/e8e1a382-f73f-11e5-85d9-9eb18edda793.png)

Any ideas why?

**Comment by keith-hall** [comment]
Are there any errors from Package Control in the Sublime Text console (`View` menu -> `Show Console`)?

**Comment by davidhq** [comment]
Actually yes:

```
reloading settings Packages/User/Fetch.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 551, in run_
    return self.run(**args)
  File "/Users/david/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl_build_system_hack.py", line 16, in run
    RESULTS.put(cmd)
AttributeError: 'NoneType' object has no attribute 'put'
```

I have YAML format, I renamed the file to Solidity.YAML but it's the same problem...

**Comment by davidhq** [comment]
No...

**Comment by keith-hall** [comment]
Is PackageDev in your list of installed packages (Package Control preferences) or ignored packages (User preferences)?

**Comment by davidhq** [comment]
Hmm actually yes, I had it already installed..

Too bad Package Control doesn't tell you that, not a good UX I think... 

sorry for this
