### ISSUE TITLE
[Feature Request] Keymap to commands

### ISSUE THREAD

**Issue by Kristinita** [SublimeText/PackageDev#78]
## Request

Add quick conversation `sublime-keymap` file to `sublime-commands` file. 
## Justification

Some plugin developers not added commands in command palette. For example, developers [Macroptimize](https://github.com/bigcakes/Macroptimize/pull/1/files), [ConEmu](https://github.com/kiliwalk/Sublime_ConEmuOpen/pull/3/files), [Filefinder](https://github.com/houcheng/Filefinder/pull/1/files), [SyncFileYouWant](https://github.com/Lanceshi2/SyncFileYouWant/pull/3/files), [SublimeRestart](https://github.com/yedderson/SublimeRestart/pull/14/files) and [Zeal](https://github.com/vaanwd/Zeal/pull/22/files) packages.

This is not good, because
1. Hotkeys can be used in other plugins.
2. Captions in command palette easier to remember than hotkeys.
### Suricate framework introduction

For myself I work with commands use [Suricate](https://packagecontrol.io/packages/Suricate) framework. For example, my `suricate-profile` file:

``` json
"user_commands":
{
  "git_bash":
  {
    "caption": "Git Bash",
    "group": "main.preferences",
    "keys": ["<c>+super+keypad3"],
    "args.windows": {"cmd": ["C:\\Program Files\\Git\\git-bash.exe"], "working_dir": "${file_path}"},
    "call": "Suricate.lib.process.spawn",
    "context_menu": true
  },
}
```

Now I can run `git_bash` command in command palette, menu bar, shortcut and context menu. And I don't need to create additional files for command `git_bash`. All settings only in one file.
### Creation sublime-commands extended behavior

<kbd>Ctrl+Shift+P</kbd> → `PackageDev: Keymap to Commands` → in same package, when `Default (Operating System).sublime-keymap` files was created `Default.sublime-commands` file.

``` json
[
    {
        "keys": ["$key"],
        "command": "$command_name"
    },
    {
        "keys": ["$key"],
        "command": "$command_name"
    }
]

```

→

``` json
[
    {
        "caption": "$Package Name: $Command Name",
        "command": "$command_name",
    },
    {
        "caption": "$Package Name: $Command Name",
        "command": "$command_name"
    }
]

```

For example,

``` json
[
    {
        "keys": ["f1"],
        "command": "zeal_search_selection"
    },
    {
        "keys": ["shift+f1"],
        "command": "zeal_search"
    }
]

```

→

``` json
[
    {
        "caption": "Zeal: Zeal Search Selection",
        "command": "zeal_search_selection",
    },
    {
        "caption": "Zeal: Zeal Search",
        "command": "zeal_search"
    }
]

```

→ was opened `Default.sublime-commands` file, which may be edited, if there is a need. `Default (Operating System).sublime-keymap`, of course, not to be a deleted.

Thanks.

**Comment by FichteFoll** [comment]
I find this functionality to be too limited of scope. Your argument behind "package authors provide keybinds but don't provide commands file" doesn't help here because if they don't know about the command, they still won't add a commands file. 

Converting keymap entries to command entries isn't that hard because they are structured similarly and the subtle changes can be either mass-edited using ST's multiple selections feature or they couldn't realiably be automated anyway. This just seems like a user task that isn't feasible to automate and I highly doubt anyone would be using it.
