### ISSUE TITLE
[Question] json-tmLanguage

### ISSUE THREAD

**Issue by Kristinita** [SublimeText/PackageDev#79]
PackageDev → Snippets → [JSON Syntax Definitions](https://github.com/SublimeText/PackageDev/tree/master/Snippets/JSON%20Syntax%20Definitions). Scope for this snippets is `source.json-tmlanguage`.

Whether actual `json-tmlanguage`? Perhaps it makes sense to update the snippets for modern syntax files?

Thanks.

**Comment by FichteFoll** [comment]
I don't understand? Do you mean https://github.com/SublimeText/PackageDev/issues/67?
