### ISSUE TITLE
Keyboard Command in documentation incorrect

### ISSUE THREAD

**Issue by brockwalters** [SublimeText/PackageDev#85]
Your documentation says that the "Command Palette" can be called by using "ctrl + shift + P".

It is actually "Command + Shift + P".

**Comment by FichteFoll** [comment]
The binding is correct for Linux and Windows, but OSX uses largely different bindings.

**Comment by brockwalters** [comment]
no. the command key is not the same as the control key. there is no way in which this is correct. just put a note in for each platform's keyboard commands.

Brock Walters
Jamf
Senior Education Services Engineer
https://www.jamf.com
brock.walters@jamf.com<mailto:brock.walters@jamf.com>
612.718.5470




On Jan 24, 2017, at 1:45 AM, FichteFoll <notifications@github.com<mailto:notifications@github.com>> wrote:


The binding is correct for Linux and Windows, but OSX uses largely different bindings.

**Comment by FichteFoll** [comment]
With the rewrite of the readme (and documentation), the key bindings have been updated to name "Primary" instead of "Ctrl" or "Command" respectively.
